#pragma once

enum
{
    RET_ERROR_IO = 1,
    RET_ILLEGAL_UID,
    RET_ERROR_HTTP_PROTOCOL,
    RET_UNKNOWN_PURPOSE,
    RET_INCORRECT_BLOB,
    RET_SMALL_BUFFER,
    RET_NOTENOUGH_MEMORY,
    RET_DB_NOUSERKEY,
    RET_INCORRECT_KEY,
    RET_CANNOT_GEN_KEY,
    RET_CANNOT_EXPORT_KEY,
    RET_ERROR_HASH,
    RET_UNKNOWN_MSG_ID,
    RET_OLD_BEHIND_PROXY,
    RET_CANNOT_OBTAIN_IP,
    RET_DB_CANNOT_FIND_OUTMSG,
    RET_ERROR_BIG_DATABLOCK,
    RET_DB_ERR_GETREVERSECL,
    RET_DB_ERR_SETFILTER,
    RET_ILLEGAL_STATUS,
    RET_CANNOT_CREATE_ACCEPT_SOCKET,
    RET_CANNOT_BIND_SOCKET,
    RET_ERROR_SEND,
    RET_ERROR_RECV,
    RET_DB_ERROR_ON_SEARCH_USER,
    RET_ERROR,
    RET_DB_ERR_GET_CONTACTLIST,
    RET_ERR_CHECK_PACKET_HEADR,
    RET_ERR_RECIVE_PACKET,
    RET_ERR_UNSUPORTED_OUT_MSG,
    RET_ERR_BAD_SESSION_KEY,
    RET_ERR_DECRYPT_DATA,
    RET_HTTP_IN_PROTOCOL_1
};

class CConnection;

class CLogWriter
{
public:
	static void write(LPCTSTR szFmt, ...);
	static void log(DWORD dwMsg, CConnection* pConn = 0);
};

